'use client'

import { message } from 'antd'
import type { StoryboardRecordRow } from '~/types/business-api'
import { openImagePreviewModal } from '~/utils/openImagePreviewModal'
import {
isStoryboardImageSelected,
pickStoryboardCoverImage,
sortStoryboardImagesForParent
} from '~/utils/storyboardImageCover'
import {
fetchStoryboardRecordsForStoryboard
} from '~/utils/storyboardRecordBatch'
import { isPendingStoryboardRecord } from '~/utils/storyboardRecordPending'
import { resolveStoryboardRecordDisplayName } from '~/utils/storyboardRecordRow'
import { resolveStoryScriptSaveContext } from '~/utils/storyScriptSaveContext'
import type { EditStoryboardImageModalCtx,EditStoryboardImageModalScene } from './types'
import { STORYBOARD_GENERATED_IMAGE_DEFAULT_TITLE } from './types'
import { nextTick } from './useMirrored'

export interface StoryboardModalRecordsApi {
  currentScene: () => EditStoryboardImageModalScene
  currentStoryboardId: () => number | null
  joinAssetIds: (list: any[]) => string | undefined
  currentScriptContentForModal: () => string
  syncLocalSceneImagesFromSceneIndex: (
    sceneIdx: number,
    opts?: { preservePending?: boolean }
  ) => void
  isAutoGeneratedStoryboardImageTitle: (title: string) => boolean
  buildStoryboardImageTitleByRecordId: (sceneIdx: number) => Map<string, string>
  mapRecordRowToImageItem: (r: StoryboardRecordRow, titleById?: Map<string, string>) => any
  fetchImageRecordsForStoryboard: (
    storyboardId: number,
    options?: { force?: boolean }
  ) => Promise<StoryboardRecordRow[]>
  mapRecordRowsToImageItems: (rows: StoryboardRecordRow[], sceneIdx: number) => any[]
  resolveStoryboardRecordId: (img: any) => number | null
  syncAddedImageIdsFromList: (images: any[]) => void
  isSameStoryboardImageRecordList: (a: any[] | undefined, b: any[] | undefined) => boolean
  refreshSceneRecords: (
    sceneIdx: number,
    selectRecordId?: number | null,
    minCountBefore?: number,
    options?: { force?: boolean }
  ) => Promise<void>
  currentSceneImages: () => any[]
  currentImg: () => any | null
  showCurrentGeneratingPlaceholder: () => boolean
  isHistoryItemMain: (imageIndex: number) => boolean
  canSetMainFromHistory: (imageIndex: number) => boolean
  isHistoryItemGenerating: (imageIndex: number) => boolean
  handlePreviewCanvasImage: () => void
  handlePreviewImageUrl: (url: string) => void
  showCancelAddStoryboardImage: () => boolean
  formatDate: (dateString: string) => string
  getFirstSceneImage: (sceneIndex: number) => any | null
}

export function useStoryboardModalRecords(
  ctx: EditStoryboardImageModalCtx
): StoryboardModalRecordsApi {
  const currentScene = (): EditStoryboardImageModalScene => {
    return ctx.props().scenes[ctx.currentSceneIndex.get()] || { name: '', images: [] }
  }

  const currentStoryboardId = (): number | null => {
    const raw = (currentScene() as { storyboardId?: number | string }).storyboardId
    const id = Number(raw)
    return Number.isFinite(id) && id > 0 ? id : null
  }

  function joinAssetIds(list: any[]): string | undefined {
    const ids = list.map((x) => Number(x?.id)).filter((n) => Number.isFinite(n) && n > 0)
    return ids.length ? ids.join(',') : undefined
  }

  const currentScriptContentForModal = () =>
    (currentScene() as { scriptContent?: string }).scriptContent ?? ''

  function syncLocalSceneImagesFromSceneIndex(
    sceneIdx: number,
    opts?: { preservePending?: boolean }
  ) {
    const sceneImages = ctx.props().scenes[sceneIdx]?.images || []
    const sceneIds = new Set(sceneImages.map((img: any) => img.id).filter(Boolean))
    const pendingOnly = opts?.preservePending
      ? ctx.localSceneImages
          .get()
          .filter((img: any) => img?._pending && img?.id && !sceneIds.has(img.id))
      : []
    ctx.localSceneImages.set([...sceneImages.map((img: any) => ({ ...img })), ...pendingOnly])
    const n = ctx.localSceneImages.get().length
    if (n === 0) {
      ctx.currentImageIndex.set(0)
    } else if (ctx.currentImageIndex.get() >= n) {
      ctx.currentImageIndex.set(n - 1)
    }
  }

  /** 右侧生图接口会把 prompt 写入 userInputText，不再用作展示标题 */
  function isAutoGeneratedStoryboardImageTitle(title: string): boolean {
    const t = title.trim()
    if (!t || t === '分镜图' || t === '九宫格') return true
    return /^(分镜图|九宫格)\s*[|｜]/.test(t)
  }

  function buildStoryboardImageTitleByRecordId(sceneIdx: number): Map<string, string> {
    const map = new Map<string, string>()
    for (const im of ctx.props().scenes[sceneIdx]?.images ?? []) {
      const id = String(im?.id ?? '').trim()
      const title = String(im?.title ?? '').trim()
      if (!id || !title || isAutoGeneratedStoryboardImageTitle(title)) continue
      map.set(id, title)
    }
    return map
  }

  function mapRecordRowToImageItem(r: StoryboardRecordRow, titleById?: Map<string, string>): any {
    const url = (r.fileUrl || '').trim()
    const id = String(r.id ?? '')
    const customTitle = titleById?.get(id)?.trim()
    const title =
      customTitle ||
      resolveStoryboardRecordDisplayName(r) ||
      STORYBOARD_GENERATED_IMAGE_DEFAULT_TITLE
    void title
    return {
      id,
      url,
      thumbnail: url,
      title: customTitle || STORYBOARD_GENERATED_IMAGE_DEFAULT_TITLE,
      source: '生成记录',
      importDate: r.createTime || undefined,
      createdAt: r.createTime || undefined,
      isSelected: r.isSelected === 1,
      _generating: isPendingStoryboardRecord(r),
      _fromServer: true,
      _serverRow: r
    }
  }

  async function fetchImageRecordsForStoryboard(
    storyboardId: number,
    options?: { force?: boolean }
  ): Promise<StoryboardRecordRow[]> {
    const ctx2 = await resolveStoryScriptSaveContext(ctx.store(), ctx.route())
    if (!ctx2) return []
    return fetchStoryboardRecordsForStoryboard(ctx2, storyboardId, 'image', options)
  }

  function mapRecordRowsToImageItems(rows: StoryboardRecordRow[], sceneIdx: number): any[] {
    const titleById = buildStoryboardImageTitleByRecordId(sceneIdx)
    return rows
      .filter((r) => !!String(r?.fileUrl ?? '').trim() || isPendingStoryboardRecord(r))
      .map((r) => mapRecordRowToImageItem(r, titleById))
  }

  function resolveStoryboardRecordId(img: any): number | null {
    const fromRow = img?._serverRow?.id
    if (fromRow != null && Number.isFinite(Number(fromRow)) && Number(fromRow) > 0) {
      return Number(fromRow)
    }
    const id = Number(img?.id)
    if (img?._fromServer && Number.isFinite(id) && id > 0) return id
    return null
  }

  function syncAddedImageIdsFromList(images: any[]) {
    const next = new Set<string>()
    images.forEach((im) => {
      if (!im?.id) return
      if (isStoryboardImageSelected(im)) {
        next.add(String(im.id))
      }
    })
    ctx.addedImageIds.set(next)
  }

  function isSameStoryboardImageRecordList(a: any[] | undefined, b: any[] | undefined): boolean {
    const left = Array.isArray(a) ? a : []
    const right = Array.isArray(b) ? b : []
    if (left.length !== right.length) return false
    return left.every((item, index) => {
      const other = right[index]
      return (
        String(item?.id ?? item?.url ?? item?.thumbnail ?? '') ===
          String(other?.id ?? other?.url ?? other?.thumbnail ?? '') &&
        !!item?._generating === !!other?._generating &&
        !!item?._localGeneratingPlaceholder === !!other?._localGeneratingPlaceholder &&
        !!item?.isStoryboardImage === !!other?.isStoryboardImage &&
        isStoryboardImageSelected(item) === isStoryboardImageSelected(other)
      )
    })
  }

  async function refreshSceneRecords(
    sceneIdx: number,
    selectRecordId?: number | null,
    minCountBefore?: number,
    options?: { force?: boolean }
  ) {
    const raw = ctx.props().scenes[sceneIdx]?.storyboardId
    const id = Number(raw)
    if (!Number.isFinite(id) || id <= 0) return
    try {
      const rows = await fetchImageRecordsForStoryboard(id, { force: options?.force })
      let mapped = sortStoryboardImagesForParent(mapRecordRowsToImageItems(rows, sceneIdx))
      mapped = ctx.finalizeMappedImagesWhileGenerating(sceneIdx, mapped)
      const prevImages = ctx.props().scenes[sceneIdx]?.images
      if (isSameStoryboardImageRecordList(mapped, prevImages)) {
        syncAddedImageIdsFromList(mapped)
        return
      }
      // 同步到父组件（右侧列表三弹窗共用：以服务端记录为准）
      // 仅更新图片列表：弹窗打开/刷新生成记录不应触发保存分镜配置
      ctx.emitUpdate(sceneIdx, { images: mapped })
      syncAddedImageIdsFromList(mapped)

      await nextTick()

      if (selectRecordId != null && Number.isFinite(Number(selectRecordId))) {
        const idx = mapped.findIndex((m) => String(m.id) === String(selectRecordId))
        if (idx >= 0) {
          ctx.currentImageIndex.set(idx)
          return
        }
      }

      if (typeof minCountBefore === 'number' && mapped.length > minCountBefore) {
        ctx.currentImageIndex.set(mapped.length - 1)
      }
    } catch (e: unknown) {
      const err = e as { msg?: string; message?: string }
      message.warning(err?.msg || err?.message || '获取生成记录失败')
    }
  }

  const currentSceneImages = () => {
    return ctx.localSceneImages.get()
  }

  /** 当前选中的分镜图（与左侧「生成记录」、中间画布一致） */
  const currentImg = () => {
    const imgs = currentSceneImages()
    const i = ctx.currentImageIndex.get()
    if (!imgs.length || i < 0 || i >= imgs.length) return null
    return imgs[i]
  }

  const showCurrentGeneratingPlaceholder = () =>
    !!currentImg()?._generating && isHistoryItemGenerating(ctx.currentImageIndex.get())

  function isHistoryItemMain(imageIndex: number): boolean {
    const img = currentSceneImages()[imageIndex]
    return isStoryboardImageSelected(img)
  }

  function canSetMainFromHistory(imageIndex: number): boolean {
    const img = currentSceneImages()[imageIndex] as { url?: string } | undefined
    // 与编辑分镜视频一致：有可展示 URL 即可设主图；无 recordId 时会在确认时先 upload 落库
    if (!img?.url || isHistoryItemGenerating(imageIndex) || isHistoryItemMain(imageIndex))
      return false
    return true
  }

  function isHistoryItemGenerating(imageIndex: number): boolean {
    if (!ctx.isSceneModalImageGenerating(ctx.currentSceneIndex.get())) return false
    const images = currentSceneImages()
    const img = images[imageIndex]
    if (img?._generating) return true

    const sid = currentStoryboardId()
    const session = ctx.readSessionForScene(ctx.currentSceneIndex.get())
    const hasPendingRecord = images.some((item) => item?._generating)

    // 变清晰/多机位/九宫格会新增生成记录：有 pending 时仅在其上展示；否则展示本地占位
    if (sid != null && ctx.isModalOverlayGenerationInProgress(sid)) {
      if (hasPendingRecord) return false
      const placeholderIdx = images.findIndex((item) => item?._localGeneratingPlaceholder)
      if (placeholderIdx >= 0) return imageIndex === placeholderIdx
      return false
    }

    if (sid != null && ctx.isDialogueGenerationInProgress(sid)) {
      if (hasPendingRecord) return false
      const targetIdx = session?.imageIdx ?? ctx.currentImageIndex.get()
      return imageIndex === targetIdx
    }

    const pendingIdx = images.findIndex((item) => item?._generating)
    if (pendingIdx >= 0) return imageIndex === pendingIdx
    return imageIndex === ctx.currentImageIndex.get()
  }

  function handlePreviewCanvasImage() {
    const img = currentImg()
    const url = String(img?.url || '').trim()
    if (!url) return
    openImagePreviewModal({
      url,
      title: img?.title || '预览'
    })
  }

  function handlePreviewImageUrl(url: string) {
    const src = String(url || '').trim()
    if (!src) return
    openImagePreviewModal({
      url: src,
      title: '预览'
    })
  }

  const showCancelAddStoryboardImage = () => {
    const img = currentImg() as {
      id?: string
      _pending?: boolean
      isSelected?: boolean
      _serverRow?: { isSelected?: number | null }
    } | null
    if (!img?.id || img._pending) return false
    const id = String(img.id)
    return isStoryboardImageSelected(img) || ctx.addedImageIds.get().has(id)
  }

  const formatDate = (dateString: string) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    return date.toLocaleString('zh-CN', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const getFirstSceneImage = (sceneIndex: number) => {
    const scene = ctx.props().scenes[sceneIndex]
    return pickStoryboardCoverImage(scene?.images)
  }

  return {
    currentScene,
    currentStoryboardId,
    joinAssetIds,
    currentScriptContentForModal,
    syncLocalSceneImagesFromSceneIndex,
    isAutoGeneratedStoryboardImageTitle,
    buildStoryboardImageTitleByRecordId,
    mapRecordRowToImageItem,
    fetchImageRecordsForStoryboard,
    mapRecordRowsToImageItems,
    resolveStoryboardRecordId,
    syncAddedImageIdsFromList,
    isSameStoryboardImageRecordList,
    refreshSceneRecords,
    currentSceneImages,
    currentImg,
    showCurrentGeneratingPlaceholder,
    isHistoryItemMain,
    canSetMainFromHistory,
    isHistoryItemGenerating,
    handlePreviewCanvasImage,
    handlePreviewImageUrl,
    showCancelAddStoryboardImage,
    formatDate,
    getFirstSceneImage
  }
}
