'use client'

import { useEffect, useRef, useState } from 'react'
import { Button, Modal, Select, Tooltip, message } from 'antd'
import { CloseOutlined } from '@ant-design/icons'
import { assetUrl } from '~/utils/assetUrl'
import dialogSelectNorIconRaw from '~/assets/img/icon/dialog-select-nor.svg'
import dialogSelectSelIconRaw from '~/assets/img/icon/dialog-select-sel.svg'
import starWhiteIconRaw from '~/assets/img/icon/star_white.svg'
import { emptyImageIconUrl as emptyImageIconRaw } from '~/utils/emptyImageIcon'
import { ShimmerImage } from '~/components/common/ShimmerImage'
import { ShimmerVideo } from '~/components/common/ShimmerVideo'
import ModelSelectDropdown from './ModelSelectDropdown'
import { resolveStoryboardPanelCoverImage } from '~/utils/storyboardImageCover'
import {
  isAutoGeneratedStoryboardPanel,
  manualStoryboardTooltip
} from '~/utils/storyboardManual'
import { parseServerStoryboardId } from '~/composables/useStoryboardWorkbenchMutations'
import { useCreationStore } from '~/stores/creation'
import { skipsStoryboardImageGeneration } from '~/utils/creationModeUiRules'
import { useRouteLike } from '~/composables/useRouteLike'
import type { StoryboardPanel, StoryboardVideoPanel } from '~/types'
import { refreshStoryboardPanelsFromApiForBatchModal } from '~/utils/batchModalListRefresh'
import { useBatchStoryboardModels } from './batch-generate-storyboard/useBatchStoryboardModels'
import './BatchGenerateStoryboardModal.css'

const dialogSelectNorIcon = assetUrl(dialogSelectNorIconRaw)
const dialogSelectSelIcon = assetUrl(dialogSelectSelIconRaw)
const starWhiteIconUrl = assetUrl(starWhiteIconRaw)
const emptyImageIconUrl = assetUrl(emptyImageIconRaw)

interface Props {
  open: boolean
  mode: 'image' | 'video'
  panels?: StoryboardPanel[]
  videoPanels?: StoryboardVideoPanel[]
  title?: string
  /** 打开时是否默认全选可选项 */
  preselectAll?: boolean
  onOpenChange: (value: boolean) => void
  onConfirm?: (payload: {
    mode: 'image' | 'video'
    selectedStoryboardIds: number[]
    agent?: string
    model?: string
    videoModel?: string
    resolution?: string
    durationSeconds?: number
    /** 音画同出偏好；模型不支持时固定为 none */
    soundEffects?: 'none' | 'with-sound'
  }) => void
}

interface CardListItem {
  panel: StoryboardPanel
  panelIndex: number
  cover: string
  coverKind: 'image' | 'video'
  label: string
  canSelect: boolean
  disabledTooltip: string
}

/** 原 computed cardList：打开态刷新列表 / props 列表二选一推导 */
function computeCardList(
  mode: 'image' | 'video',
  panels: StoryboardPanel[],
  videoPanels: StoryboardVideoPanel[],
  projectCreationMode: string
): CardListItem[] {
  const creationStore = useCreationStore.getState()
  return panels.map((panel, index) => {
    const storyboardImageUrl = String(resolveStoryboardPanelCoverImage(panel)?.url ?? '').trim()
    const hasStoryboardImage = !!storyboardImageUrl
    const isAutoPanel = isAutoGeneratedStoryboardPanel(panel, creationStore)
    const videoPanel = videoPanels[index]
    const videoCover = String(
      videoPanel?.videos?.find((v) => v.isStoryboardVideo && String(v.url ?? '').trim())?.url ?? ''
    ).trim()
    const displayCover = mode === 'video' ? storyboardImageUrl || videoCover : storyboardImageUrl
    const coverKind =
      mode === 'video' && !hasStoryboardImage && videoCover
        ? ('video' as const)
        : ('image' as const)

    let canSelect = isAutoPanel
    let disabledTooltip = ''
    if (mode === 'video') {
      if (!isAutoPanel) {
        canSelect = false
        disabledTooltip = manualStoryboardTooltip('video')
      } else if (!hasStoryboardImage && !skipsStoryboardImageGeneration(projectCreationMode)) {
        // 专业版 / 多参数不出分镜图，批量出片不要求分镜图
        canSelect = false
        disabledTooltip = '需要先生成当前分镜视频对应的分镜图'
      }
    } else if (!isAutoPanel) {
      canSelect = false
      disabledTooltip = manualStoryboardTooltip('image')
    }

    return {
      panel,
      panelIndex: index,
      cover: displayCover,
      coverKind,
      label: panel.title || `分镜${index + 1}`,
      canSelect,
      disabledTooltip
    }
  })
}

export function BatchGenerateStoryboardModal({
  open,
  mode,
  panels = [],
  videoPanels = [],
  title = '',
  preselectAll = false,
  onOpenChange,
  onConfirm
}: Props) {
  const route = useRouteLike()
  const routeRef = useRef(route)
  routeRef.current = route

  // 订阅手动分镜 id 列表：变化时刷新 canSelect 推导
  useCreationStore((s) => s.manualStoryboardIds)
  const projectCreationMode = useCreationStore(
    (s) => s.formData.globalSetting?.creationMode || 'i2v'
  )

  const modalOpenInitGenRef = useRef(0)
  const [listLoading, setListLoading] = useState(false)
  const listLoadingRef = useRef(false)
  const [refreshedPanels, setRefreshedPanelsState] = useState<StoryboardPanel[] | null>(null)
  const refreshedPanelsRef = useRef<StoryboardPanel[] | null>(null)
  const [refreshedVideoPanels, setRefreshedVideoPanelsState] = useState<
    StoryboardVideoPanel[] | null
  >(null)
  const refreshedVideoPanelsRef = useRef<StoryboardVideoPanel[] | null>(null)

  const setListLoadingBoth = (v: boolean) => {
    listLoadingRef.current = v
    setListLoading(v)
  }
  const setRefreshedPanels = (v: StoryboardPanel[] | null) => {
    refreshedPanelsRef.current = v
    setRefreshedPanelsState(v)
  }
  const setRefreshedVideoPanels = (v: StoryboardVideoPanel[] | null) => {
    refreshedVideoPanelsRef.current = v
    setRefreshedVideoPanelsState(v)
  }

  const [selectedIds, setSelectedIdsState] = useState<Set<string>>(new Set())
  const selectedIdsRef = useRef<Set<string>>(new Set())
  const setSelectedIds = (v: Set<string>) => {
    selectedIdsRef.current = v
    setSelectedIdsState(v)
  }

  /** 异步流程（打开初始化）内读最新 props */
  const propsSnapshotRef = useRef({ open, mode, panels, videoPanels, preselectAll })
  propsSnapshotRef.current = { open, mode, panels, videoPanels, preselectAll }

  const models = useBatchStoryboardModels({ projectCreationMode, routeRef })
  const {
    agent,
    model,
    loadImageAgents,
    initImageModelSelection,
    videoModel,
    videoModelOptions,
    videoModelsLoading,
    videoModelDropdownExpanded,
    setVideoModelDropdownExpanded,
    videoQuality,
    setVideoQuality,
    videoDuration,
    setVideoDuration,
    videoAudio,
    setVideoAudio,
    videoQualityOptions,
    videoDurationOptions,
    videoAudioOptions,
    videoConfigShowAudio,
    videoConfigShowDuration,
    selectedVideoModel,
    handleSelectVideoModel,
    initVideoModelSelection,
    invalidateVideoModelLoad
  } = models

  const modalTitle = title ? title : mode === 'image' ? '批量生成分镜图' : '批量生成分镜视频'

  const modalSubtitle =
    mode === 'image' ? '生成结果将更新到分镜图，历史记录可在生图历史中查看' : ''

  const effectivePanels = refreshedPanels ?? panels
  const effectiveVideoPanels = refreshedVideoPanels ?? videoPanels

  const cardList = computeCardList(mode, effectivePanels, effectiveVideoPanels, projectCreationMode)

  /** 异步初始化（resetSelectionOnOpen）用：从 ref 快照推导当前列表 */
  function computeCardListLive(): CardListItem[] {
    const snap = propsSnapshotRef.current
    return computeCardList(
      snap.mode,
      refreshedPanelsRef.current ?? snap.panels,
      refreshedVideoPanelsRef.current ?? snap.videoPanels,
      useCreationStore.getState().formData.globalSetting?.creationMode || 'i2v'
    )
  }

  const selectableCount = cardList.filter((c) => c.canSelect).length

  const withImageCount = cardList.filter((c) => !!c.cover).length

  const pendingCount = cardList.filter((c) => {
    if (!c.canSelect) return false
    const vp = effectiveVideoPanels[c.panelIndex]
    const hasVideo = (vp?.videos || []).some(
      (v) => v.isStoryboardVideo && String(v.url ?? '').trim()
    )
    return !hasVideo
  }).length

  const isAllSelectableChecked = (() => {
    const selectable = cardList.filter((c) => c.canSelect)
    if (selectable.length === 0) return false
    return selectable.every((c) => selectedIds.has(c.panel.id))
  })()

  function toggleSelect(id: string) {
    const item = cardList.find((c) => c.panel.id === id)
    if (!item?.canSelect) return
    const next = new Set(selectedIdsRef.current)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setSelectedIds(next)
  }

  function onCardClick(item: { panel: StoryboardPanel; canSelect: boolean }) {
    if (item.canSelect) toggleSelect(item.panel.id)
  }

  function toggleSelectAll() {
    const selectable = cardList.filter((c) => c.canSelect).map((c) => c.panel.id)
    if (selectable.every((id) => selectedIdsRef.current.has(id))) {
      const next = new Set(selectedIdsRef.current)
      selectable.forEach((id) => next.delete(id))
      setSelectedIds(next)
    } else {
      const next = new Set(selectedIdsRef.current)
      selectable.forEach((id) => next.add(id))
      setSelectedIds(next)
    }
  }

  function handleCancel() {
    onOpenChange(false)
  }

  function resetSelectionOnOpen() {
    if (propsSnapshotRef.current.preselectAll) {
      setSelectedIds(
        new Set(
          computeCardListLive()
            .filter((c) => c.canSelect)
            .map((c) => c.panel.id)
        )
      )
    } else {
      setSelectedIds(new Set())
    }
  }

  async function loadModalListData() {
    setListLoadingBoth(true)
    try {
      const loaded = await refreshStoryboardPanelsFromApiForBatchModal(routeRef.current)
      if (!loaded) {
        message.warning('缺少项目信息，请从「我的作品」打开作品后再操作')
        return
      }
      setRefreshedPanels(loaded)
      setRefreshedVideoPanels(
        useCreationStore.getState().formData.storyboardVideo.panels as StoryboardVideoPanel[]
      )
    } catch (e: unknown) {
      const err = e as { msg?: string; message?: string }
      message.warning(err?.msg || err?.message || '刷新分镜列表失败')
    } finally {
      setListLoadingBoth(false)
    }
  }

  function clearModalListCache() {
    setRefreshedPanels(null)
    setRefreshedVideoPanels(null)
  }

  async function handleModalContentInit() {
    if (!propsSnapshotRef.current.open) return
    const gen = ++modalOpenInitGenRef.current
    await loadModalListData()
    if (gen !== modalOpenInitGenRef.current) return
    resetSelectionOnOpen()
    if (propsSnapshotRef.current.mode === 'image') {
      await loadImageAgents()
      if (gen !== modalOpenInitGenRef.current) return
      await initImageModelSelection()
      return
    }
    if (propsSnapshotRef.current.mode === 'video') {
      await initVideoModelSelection()
    }
  }

  function handleModalAfterOpenChange(nextOpen: boolean) {
    if (!nextOpen) {
      setVideoModelDropdownExpanded(false)
      modalOpenInitGenRef.current++
      invalidateVideoModelLoad()
      clearModalListCache()
    }
  }

  function handleConfirm() {
    if (listLoadingRef.current) return
    if (selectedIdsRef.current.size === 0) return
    const selectedStoryboardIds = [...selectedIdsRef.current]
      .map((id) => parseServerStoryboardId(id))
      .filter((sid): sid is number => sid != null)
    if (!selectedStoryboardIds.length) {
      message.warning('所选分镜尚未保存到服务器')
      return
    }
    if (mode === 'image' && !String(agent || '').trim()) {
      message.warning('请选择智能体')
      return
    }
    if (mode === 'video' && !String(videoModel || '').trim()) {
      message.warning('请选择生视频模型')
      return
    }
    const durationSec = Number(videoDuration)
    const soundEffects: 'none' | 'with-sound' = videoConfigShowAudio
      ? videoAudio === 'with_audio'
        ? 'with-sound'
        : 'none'
      : 'none'
    onConfirm?.({
      mode,
      selectedStoryboardIds,
      ...(mode === 'image'
        ? { agent, model }
        : {
            videoModel,
            resolution: String(videoQuality || '').trim().toLowerCase() || undefined,
            soundEffects,
            ...(videoConfigShowDuration && Number.isFinite(durationSec) && durationSec > 0
              ? { durationSeconds: durationSec }
              : {})
          })
    })
    onOpenChange(false)
  }

  // 原 watch(() => props.open, ..., { immediate: true })
  useEffect(() => {
    if (!open) {
      handleModalAfterOpenChange(false)
      return
    }
    void handleModalContentInit()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // 原 watch(projectCreationMode)
  const creationModeFirstRunRef = useRef(true)
  useEffect(() => {
    if (creationModeFirstRunRef.current) {
      creationModeFirstRunRef.current = false
      return
    }
    if (propsSnapshotRef.current.open && propsSnapshotRef.current.mode === 'video') {
      void initVideoModelSelection()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectCreationMode])

  const selectPopupProps = { classNames: { popup: { root: 'bgsm-select-popup' } } }

  const renderCardMedia = (item: CardListItem) => (
    <>
      {item.cover && item.coverKind === 'video' ? (
        <ShimmerVideo
          src={item.cover}
          videoClass="bgsm-card-img"
          objectFit="cover"
          revealDirection="fade"
        />
      ) : item.cover ? (
        <ShimmerImage
          src={item.cover}
          alt={item.label}
          imgClass="bgsm-card-img"
          objectFit="cover"
          revealDirection="fade"
        />
      ) : (
        <div className="bgsm-card-empty">
          <img
            src={emptyImageIconUrl}
            alt=""
            className="empty-image-icon empty-image-icon--xl bgsm-card-empty__icon"
          />
        </div>
      )}
    </>
  )

  return (
    <Modal
      open={open}
      width={1100}
      footer={null}
      title={null}
      closable={false}
      className="batch-generate-storyboard-modal"
      wrapClassName="create-flow-modal batch-generate-storyboard-wrap"
      forceRender
      onCancel={handleCancel}
      afterOpenChange={handleModalAfterOpenChange}
    >
      <div className="bgsm">
        <header className="bgsm-header">
          <div className="bgsm-title-wrap">
            <h2 className="bgsm-title">{modalTitle}</h2>
            {modalSubtitle ? <p className="bgsm-subtitle">{modalSubtitle}</p> : null}
          </div>
          <button type="button" className="bgsm-close" aria-label="关闭" onClick={handleCancel}>
            <CloseOutlined />
          </button>
        </header>

        <div className="bgsm-toolbar">
          <button type="button" className="bgsm-select-all" onClick={toggleSelectAll}>
            <img
              className="bgsm-check-icon"
              src={isAllSelectableChecked ? dialogSelectSelIcon : dialogSelectNorIcon}
              alt=""
            />
            <span className="bgsm-select-all-text">
              全选 ({selectedIds.size}/{selectableCount})
            </span>
          </button>
          {mode === 'video' ? (
            <span className="bgsm-pending">待处理 ({pendingCount})</span>
          ) : (
            <span className="bgsm-pending bgsm-pending--muted">
              已有图片 ({withImageCount}/{effectivePanels.length})
            </span>
          )}
        </div>

        <div className="bgsm-body">
          <div className="bgsm-grid">
            {cardList.map((item) =>
              !item.canSelect ? (
                <Tooltip key={item.panel.id} title={item.disabledTooltip}>
                  <article className="bgsm-card bgsm-card--disabled">
                    <div className="bgsm-card-media">{renderCardMedia(item)}</div>
                    <div className="bgsm-card-meta">
                      <div className="bgsm-card-name">{item.label}</div>
                    </div>
                  </article>
                </Tooltip>
              ) : (
                <article
                  key={item.panel.id}
                  className={
                    selectedIds.has(item.panel.id)
                      ? 'bgsm-card bgsm-card--selected'
                      : 'bgsm-card'
                  }
                  onClick={() => onCardClick(item)}
                >
                  <div className="bgsm-card-media">
                    {renderCardMedia(item)}
                    <img
                      className="bgsm-card-select"
                      src={selectedIds.has(item.panel.id) ? dialogSelectSelIcon : dialogSelectNorIcon}
                      alt=""
                    />
                  </div>
                  <div className="bgsm-card-meta">
                    <div className="bgsm-card-name">{item.label}</div>
                  </div>
                </article>
              )
            )}
          </div>
        </div>

        <footer className="bgsm-footer">
          <div
            className={
              mode === 'video' ? 'bgsm-footer-left bgsm-footer-left--video' : 'bgsm-footer-left'
            }
          >
            {mode === 'video' ? (
              <>
                <div className="bgsm-field bgsm-field--video-model">
                  <label className="bgsm-label">生视频模型</label>
                  {videoModelOptions.length ? (
                    <ModelSelectDropdown
                      value={selectedVideoModel}
                      options={videoModelOptions}
                      expanded={videoModelDropdownExpanded}
                      onToggle={() => setVideoModelDropdownExpanded(!videoModelDropdownExpanded)}
                      onClose={() => setVideoModelDropdownExpanded(false)}
                      onSelect={handleSelectVideoModel}
                    />
                  ) : videoModelsLoading ? (
                    <div className="bgsm-video-model-placeholder">加载中…</div>
                  ) : (
                    <div className="bgsm-video-model-placeholder">暂无可用模型</div>
                  )}
                </div>
                {videoQualityOptions.length ? (
                  <div className="bgsm-field bgsm-field--video-param">
                    <label className="bgsm-label">清晰度</label>
                    <Select
                      value={videoQuality}
                      onChange={(v) => setVideoQuality(v)}
                      className="bgsm-select"
                      {...selectPopupProps}
                      size="large"
                      options={videoQualityOptions}
                      disabled={!videoQualityOptions.length}
                    />
                  </div>
                ) : null}
                {videoConfigShowDuration && videoDurationOptions.length ? (
                  <div className="bgsm-field bgsm-field--video-param">
                    <label className="bgsm-label">时长</label>
                    <Select
                      value={videoDuration}
                      onChange={(v) => setVideoDuration(String(v))}
                      className="bgsm-select"
                      {...selectPopupProps}
                      size="large"
                      options={videoDurationOptions}
                      disabled={!videoDurationOptions.length}
                    />
                  </div>
                ) : null}
                {videoConfigShowAudio && videoAudioOptions.length ? (
                  <div className="bgsm-field bgsm-field--video-param">
                    <label className="bgsm-label">音频</label>
                    <Select
                      value={videoAudio}
                      onChange={(v) => setVideoAudio(v)}
                      className="bgsm-select"
                      {...selectPopupProps}
                      size="large"
                      options={videoAudioOptions}
                      disabled={!videoAudioOptions.length}
                    />
                  </div>
                ) : null}
              </>
            ) : null}
          </div>
          <div className="bgsm-actions">
            <Button className="bgsm-btn-cancel" onClick={handleCancel}>
              <div className="text-gradient">取消</div>
            </Button>
            <Button
              type="primary"
              className="bgsm-btn-ok"
              disabled={selectedIds.size === 0 || listLoading}
              onClick={handleConfirm}
              icon={mode === 'video' ? <img src={starWhiteIconUrl} alt="" /> : undefined}
            >
              批量生成
            </Button>
          </div>
        </footer>
      </div>
    </Modal>
  )
}

export default BatchGenerateStoryboardModal
