import { parseServerStoryboardId } from '~/composables/useStoryboardWorkbenchMutations'
import type { StoryboardPanel } from '~/types'
import type { useCreationStore } from '~/stores/creation'

type CreationStore = ReturnType<typeof useCreationStore>

export function isManualStoryboardId(store: CreationStore, storyboardId: number): boolean {
  const sid = Number(storyboardId)
  if (!Number.isFinite(sid) || sid <= 0) return false
  return store.manualStoryboardIds.includes(sid)
}

export function isAutoGeneratedStoryboardPanel(
  panel: StoryboardPanel,
  store: CreationStore
): boolean {
  const sid = parseServerStoryboardId(panel.id)
  if (sid == null) return false
  return !isManualStoryboardId(store, sid)
}

export function manualStoryboardTooltip(mode: 'image' | 'video'): string {
  return mode === 'image'
    ? '暂不支持手动添加的分镜脚本'
    : '暂不支持手动添加的分镜视频'
}
